babylonlabs-io/babylon-toolkit

- package-lock.json
- packages/babylon-proto-ts/README.md
- packages/babylon-proto-ts/src/constants.ts
- packages/babylon-proto-ts/src/lib/client.ts
- packages/babylon-proto-ts/src/lib/messages.ts
- packages/babylon-proto-ts/src/lib/utils/amino.ts
- packages/babylon-proto-ts/src/lib/utils/index.ts
- packages/babylon-proto-ts/src/lib/utils/normalize.ts
- packages/babylon-proto-ts/src/lib/utils/registry.ts
- packages/babylon-proto-ts/tsconfig.lib.json
Adds a support for `BABY` staking
> feat: Babylon SDK Staking

- package-lock.json
- packages/babylon-core-ui/package.json
> feat(packages): release core-ui

- packages/babylon-core-ui/package.json
- packages/babylon-proto-ts/package.json
> fix(packages): update github url

- package-lock.json
- packages/babylon-core-ui/package.json
- packages/babylon-proto-ts/package.json
- scripts/release.ts
- tsconfig.json
Fixes two things:
* The custom build command from proto-ts isn't generating dist output.
* Accidentally release non-changed packages.
> fix(packages): fix proto-ts release

- packages/babylon-core-ui/public/images/status/warning_dark2.svg
- packages/babylon-core-ui/src/components/FeeItem/FeeItem.stories.tsx
- packages/babylon-core-ui/src/components/FeeItem/FeeItem.tsx
- packages/babylon-core-ui/src/components/Warning/Warning.css
- packages/babylon-core-ui/src/components/Warning/Warning.stories.tsx
- packages/babylon-core-ui/src/components/Warning/Warning.tsx
- packages/babylon-core-ui/src/components/Warning/index.tsx
- packages/babylon-core-ui/src/elements/Table/Table.stories.tsx
- packages/babylon-core-ui/src/elements/Table/Table.tsx
- packages/babylon-core-ui/src/elements/Table/index.ts
- packages/babylon-core-ui/src/index.tsx
- packages/babylon-core-ui/src/utils/constants.ts
- packages/babylon-core-ui/src/utils/helpers.ts
- packages/babylon-core-ui/src/widgets/sections/FeesSection/BBNFeeAmount.tsx
- packages/babylon-core-ui/src/widgets/sections/FeesSection/BTCFeeAmount.tsx
- packages/babylon-core-ui/src/widgets/sections/FeesSection/BTCFeeRate.tsx
- packages/babylon-core-ui/src/widgets/sections/FeesSection/index.ts
- packages/babylon-core-ui/src/widgets/sections/PreviewModal/PreviewModal.tsx
- packages/babylon-core-ui/src/widgets/sections/RewardsPreviewModal/RewardsPreviewModal.stories.tsx
- packages/babylon-core-ui/src/widgets/sections/RewardsPreviewModal/RewardsPreviewModal.tsx
> feat(packages): add rewards modal

- packages/babylon-core-ui/src/widgets/sections/FeesSection/FeesSection.stories.tsx
- packages/babylon-core-ui/src/widgets/sections/FeesSection/FeesSection.tsx
> feat(packages): add baby fees

- packages/babylon-core-ui/src/elements/FinalityProviderItem/FinalityProviderItem.tsx
- packages/babylon-core-ui/src/elements/ProvidersList/ProvidersList.tsx
- packages/babylon-core-ui/src/widgets/sections/FinalityProviderSubsection/FinalityProviderSubsection.stories.tsx
- packages/babylon-core-ui/src/widgets/sections/FinalityProviderSubsection/FinalityProviderSubsection.tsx
> feat(packages): allow fp item without chain or bsn

- packages/babylon-core-ui/src/index.tsx
- packages/babylon-core-ui/src/utils/constants.ts
- packages/babylon-core-ui/src/widgets/sections/ValidatorSelector/ValidatorSelector.stories.tsx
- packages/babylon-core-ui/src/widgets/sections/ValidatorSelector/ValidatorSelector.tsx
- packages/babylon-core-ui/src/widgets/sections/ValidatorSelector/index.tsx
> feat(packages): add validator selector

- packages/babylon-core-ui/src/components/Table/Table.css
- packages/babylon-core-ui/src/components/Table/Table.stories.tsx
- packages/babylon-core-ui/src/components/Table/Table.tsx
- packages/babylon-core-ui/src/components/Table/components/Cell.tsx
- packages/babylon-core-ui/src/components/Table/components/Column.tsx
- packages/babylon-core-ui/src/components/Table/components/Row.tsx
- packages/babylon-core-ui/src/components/Table/types/index.ts
- packages/babylon-core-ui/src/hooks/index.ts
- packages/babylon-core-ui/src/hooks/useFrozenColumns.ts
> feat(packages): frozen table column

- packages/babylon-core-ui/src/widgets/sections/AmountSubsection/AmountSubsection.stories.tsx
- packages/babylon-core-ui/src/widgets/sections/AmountSubsection/AmountSubsection.tsx
> feat(packages): allows AmountSubsection to have different prefixes, improves stories, bugfixing

- package-lock.json
- packages/babylon-campaigns/package.json
this PR changes the babylon campaigns config name
> fix(packages): update babylon campaigns config

- packages/babylon-core-ui/src/components/Avatar/ValidatorAvatar.stories.tsx
- packages/babylon-core-ui/src/components/Avatar/ValidatorAvatar.tsx
- packages/babylon-core-ui/src/components/Avatar/index.ts
- packages/babylon-core-ui/src/components/List/List.stories.tsx
- packages/babylon-core-ui/src/components/List/StatItem.tsx
- packages/babylon-core-ui/src/components/List/index.ts
- packages/babylon-core-ui/src/components/index.ts
> feat(packages): add validator avatar, statitem

- packages/babylon-core-ui/src/components/Form/Select.css
- packages/babylon-core-ui/src/components/Popover/Popover.css
- packages/babylon-core-ui/src/components/Popover/Popover.tsx
fixes z-index on select so that it shows up over modals
> feat(packages): fix z-index on select

- packages/babylon-proto-ts/src/lib/rpc/baby.ts
- packages/babylon-proto-ts/src/lib/rpc/index.ts
Part of https://github.com/babylonlabs-io/simple-staking/issues/1502
> feat(packages): add get block height babylon rpc client methods

- packages/babylon-core-ui/src/elements/FinalityProviderItem/FinalityProviderItem.tsx
> feat(packages): flip fps logos for chain logos

- packages/babylon-core-ui/src/components/Form/Select.css
- packages/babylon-core-ui/src/components/Form/Select.stories.tsx
- packages/babylon-core-ui/src/components/Form/Select.tsx
> feat(packages): truncate select logn text

- services/simple-staking/src/ui/common/components/Multistaking/FinalityProviders/FinalityProviderTable.tsx
FP can deselect when in grid view
> fix(packages): deselect fp

- services/simple-staking/src/ui/common/components/Multistaking/FinalityProviders/FinalityProviderFilter.tsx
- services/simple-staking/src/ui/common/components/Multistaking/MultistakingForm/FinalityProvidersSection.tsx
- services/simple-staking/src/ui/common/components/Staking/FinalityProviders/FinalityProviderFilter.tsx
- services/simple-staking/src/ui/common/constants.ts
- services/simple-staking/src/ui/common/services/finalityProviderFilterService.ts
- services/simple-staking/src/ui/common/state/FinalityProviderBsnState.tsx
https://github.com/user-attachments/assets/9c90a259-1e47-4c50-8c71-4500ec86a7f5
tested both phase 2 and phase 3
> fix: allowlist filter

- services/simple-staking/src/ui/common/components/Wallet/Connect.tsx
resolves: https://github.com/babylonlabs-io/babylon-toolkit/pull/151#issuecomment-3266273082
(accidently merged https://github.com/babylonlabs-io/babylon-toolkit/pull/151)
> fix(packages): remove wallet tooltip from header

- services/simple-staking/src/ui/common/state/FinalityProviderState.tsx
- services/simple-staking/src/ui/common/utils/bsnFpGroupingUtils.tsx
> fix(packages): fp not showing in phase 2 delegation

- packages/babylon-core-ui/src/widgets/sections/FeesSection/FeesSection.tsx
- services/simple-staking/src/ui/baby/widgets/ValidatorField/index.tsx
- services/simple-staking/src/ui/common/components/FAQ/Section.tsx
- services/simple-staking/src/ui/common/components/Footer/Footer.tsx
- services/simple-staking/src/ui/common/components/Multistaking/FinalityProviderField/FinalityProviderModal.tsx
- services/simple-staking/src/ui/common/components/Multistaking/FinalityProviders/FinalityProviderTable.tsx
- services/simple-staking/src/ui/common/components/Multistaking/MultistakingForm/ConnectButton.tsx
- services/simple-staking/src/ui/common/components/Staking/FinalityProviders/FinalityProviderColumns.tsx
- services/simple-staking/src/ui/common/components/Tabs/Tabs.tsx
- services/simple-staking/src/ui/common/components/ValidatorSelector/columnRenderers.tsx
- services/simple-staking/src/ui/common/components/Wallet/Connect.tsx
> feat(packages): design tweaks and fixes

- services/simple-staking/src/ui/common/services/bsnService.ts
resolves: https://github.com/babylonlabs-io/babylon-toolkit/issues/183
> fix(packages): make modalTitle dynamic

- packages/babylon-core-ui/src/components/Dialog/Dialog.tsx
- packages/babylon-core-ui/src/components/Dialog/components/DialogHeader.tsx
- packages/babylon-core-ui/src/components/Form/components/Toggle.tsx
- packages/babylon-core-ui/src/widgets/sections/WalletMenu/components/WalletMenuCard.tsx
- packages/babylon-wallet-connector/src/components/ChainButton/index.tsx
- packages/babylon-wallet-connector/src/components/Chains/index.tsx
- packages/babylon-wallet-connector/src/components/Error/index.tsx
- packages/babylon-wallet-connector/src/components/ExternalWallets/index.tsx
- packages/babylon-wallet-connector/src/components/TermsOfService/index.tsx
- packages/babylon-wallet-connector/src/components/WalletButton/index.tsx
- services/simple-staking/e2e/fixtures/wallet_balance.selectors.ts
- services/simple-staking/e2e/fixtures/wallet_balance.ts
- services/simple-staking/e2e/fixtures/wallet_connect.selectors.ts
- services/simple-staking/e2e/fixtures/wallet_connect.ts
- services/simple-staking/e2e/specs/balanceAddress.spec.ts
- services/simple-staking/src/ui/common/components/Modals/ErrorModal.tsx
- services/simple-staking/src/ui/common/components/Multistaking/MultistakingForm/ConnectButton.tsx
- services/simple-staking/src/ui/common/components/Wallet/Connect.tsx
- Added `data-testid` to necessary components
- Switched selectors to `data-testid`
> test(packages): enable e2e tests

- services/simple-staking/e2e/fixtures/wallet_balance.selectors.ts
- services/simple-staking/e2e/fixtures/wallet_connect.selectors.ts
- services/simple-staking/e2e/fixtures/wallet_connect.ts
- services/simple-staking/src/ui/baby/layout.tsx
- services/simple-staking/src/ui/baby/widgets/StakingForm/index.tsx
- services/simple-staking/src/ui/common/components/FAQ/FAQ.tsx
- services/simple-staking/src/ui/common/components/Tabs/Tabs.tsx
- services/simple-staking/src/ui/globals.css
- services/simple-staking/tests/services/finalityProviderFilterService.test.ts
- services/simple-staking/tests/utils/formatCurrency.test.ts
> feat(packages): remove chin on form, fix FAQ separator color

- services/simple-staking/src/ui/common/components/Banner/Banner.tsx
> feat(packages): change copy for sunset message

- packages/babylon-core-ui/src/components/BorrowCard/BorrowCard.stories.tsx
- packages/babylon-core-ui/src/components/BorrowCard/BorrowCard.tsx
- packages/babylon-core-ui/src/components/BorrowCard/index.tsx
- packages/babylon-core-ui/src/components/Icons/PlusIcon.stories.tsx
- packages/babylon-core-ui/src/components/Icons/common/PlusIcon.tsx
- packages/babylon-core-ui/src/components/Icons/index.ts
- packages/babylon-core-ui/src/components/index.ts
- packages/babylon-core-ui/src/index.tsx
- routes/vault/src/VaultLayout.tsx
- routes/vault/src/components/ui/Borrow.tsx
- routes/vault/src/components/ui/index.ts
> feat(packages): borrow page add new borrow button

- package-lock.json
- packages/babylon-core-ui/src/components/BorrowCard/BorrowCard.tsx
- packages/babylon-core-ui/src/elements/ProviderItem/ProviderItem.stories.tsx
- packages/babylon-core-ui/src/elements/ProviderItem/ProviderItem.tsx
- packages/babylon-core-ui/src/elements/ProviderItem/index.tsx
- packages/babylon-core-ui/src/elements/StatusBadge/StatusBadge.stories.tsx
- packages/babylon-core-ui/src/elements/StatusBadge/StatusBadge.tsx
- packages/babylon-core-ui/src/elements/StatusBadge/index.tsx
- packages/babylon-core-ui/src/index.tsx
- routes/vault/src/components/ui/Borrow.tsx
- routes/vault/src/mockData/vaultActivities.ts
- routes/vault/src/vite-env.d.ts
the UI is abit different from the design as we are just using the existing components, will change later when the design is confirmed
> feat: borrow activity card

- services/simple-staking/src/ui/baby/components/CoStakingBoostSection/index.tsx
- services/simple-staking/src/ui/common/state/CoStakingState.tsx
- services/simple-staking/src/ui/common/state/index.tsx
- added `CoStakingState` provider
- updated `CoStakingBoostSection` to use the new state
> feat(packages): add CoStakingState

- package-lock.json
- packages/babylon-bsn-registry/project.json
- packages/babylon-core-ui/package.json
- packages/babylon-core-ui/project.json
- packages/babylon-proto-ts/project.json
- packages/babylon-wallet-connector/package.json
- packages/babylon-wallet-connector/project.json
- routes/vault/project.json
- services/simple-staking/project.json
- tools/eslint-config/base.js
Enforce import rules with eslint. You should see something like this error when it was triggered.
Also dedupe `@scure/bip32`.
> fix(build): enforce build relationship
